Agenda.MVC/ViewModels/Phonebook/PhonebookSearchViewModel.cs
using System;
using System.ComponentModel;

namespace Agenda.MVC.ViewModels
{
    public class PhonebookSearchViewModel
    {

        [DisplayName("ID")]
        public string IdContato { get; set; }

        [DisplayName("Nome")]
        public string NomeContato { get; set; }

        [DisplayName("DDD")]
        public string Ddd { get; set; }

        [DisplayName("Número telefone")]
        public string NumeroTelefone { get; set; }

        public int Page { get; set; }
        public int HowManyPages { get; private set; }

        public void CountPages(int take, int total)
        {
            HowManyPages = Convert.ToInt32(Math.Ceiling(Convert.ToDecimal(total) / Convert.ToDecimal(take)));
        }

    }
}

Agenda.MVC/ViewModels/Phonebook/PhonebookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Agenda.MVC.ViewModels.Contact;

namespace Agenda.MVC.ViewModels
{
    public class PhonebookViewModel
    {

        public PhonebookSearchViewModel SearchParameters { get; set; }
        public IEnumerable<ContactViewModel> Contacts { get; set; }

    }
}

Agenda.MVC/Controllers/StandardUser/PhonebookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Agenda.MVC.ApiHttpServices;
using Agenda.MVC.ViewModels;
using Agenda.MVC.ViewModels.ApiResponse;
using Agenda.MVC.ViewModels.Contact;
using Agenda.MVC.ViewModels.ContactTelephone;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Agenda.MVC.Controllers
{
    [Authorize(Roles = "STANDARD USER")]
    [Route("agenda")]
    public class PhonebookController : Controller
    {
        private readonly PhonebookService _phonebookService;
        private readonly IMapper _mapper;

        public PhonebookController(PhonebookService phonebookService, IMapper mapper)
        {
            _phonebookService = phonebookService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index([Bind(Prefix = nameof(PhonebookViewModel.SearchParameters))] PhonebookSearchViewModel searchParameters)
        {
            IEnumerable<ContactViewModel> contacts = new List<ContactViewModel>();

            var contactPagination = await _phonebookService.GetContactPage(searchParameters);

            if (contactPagination.Data != null)
            {
                contacts = contactPagination.Data;
                searchParameters.CountPages(7, contactPagination.Total);
                if (searchParameters.Page == 0)
                    searchParameters.Page = 1;
            }

            var model = new PhonebookViewModel()
            {
                SearchParameters = searchParameters,    
                Contacts = contacts
            };

            return View(model);
        }

        [HttpGet]
        [Route("detalhes/{id:int}")]
        public async Task<ActionResult> Details(int id)
        {
            var contactVm = await _phonebookService.GetContact(id);

            return View("_ContactDetails", contactVm);
        }

        [HttpGet]
        [Route("form/{id:int}")]
        public async Task<ActionResult> Form(int id)
        {
            ContactFormViewModel contactFormVm = new ContactFormViewModel();
            ViewBag.telephoneTypes = await GetTelephoneTypeSelectList();

            if (id != 0)
            {
                var contactVm = await _phonebookService.GetContact(id);
                contactFormVm = _mapper.Map<ContactFormViewModel>(contactVm);
            }

            return View("_ContactForm", contactFormVm);
        }

        [HttpPost]
        [Route("form/{id:int}")]
        public async Task<ActionResult> Form(ContactFormViewModel model, string option = "save")
        {
            ViewBag.telephoneTypes = await GetTelephoneTypeSelectList();

            if (option.Equals("save"))
            {
                ApiResponseViewModel<ContactViewModel> apiResponse;

                if (model.Id == 0)
                {
                    apiResponse = await _phonebookService.AddContact(model);
                    TempData.Add("toast", "Contato adicionado com sucesso");
                }
                else
                {
                    apiResponse = await _phonebookService.UpdateContact(model);
                    TempData.Add("toast", "Contato atualizado com sucesso");
                }

                if (apiResponse.HasError)
                {
                    apiResponse.AddErrorsToModelState(ModelState);
                    TempData.Remove("toast");
                    return View("_ContactForm", model);
                }

                return RedirectToAction("Index");
            }

            if (option.Equals("addTelephone"))
            {
                ModelState.Clear();
                model.Telephones.Add(new ContactTelephoneFormViewModel());
            }

            if (option.Contains("removeTelephone"))
            {
                int indexRemovedTelephone = int.Parse(option.Split("|")[1]);
                ModelState.Clear();
                model.Telephones.RemoveAt(indexRemovedTelephone);
            }

            return View("_ContactForm", model);
        }

        [HttpPost]
        [Route("remover")]
        public async Task<ActionResult> RemoveContact(int id)
        {
            await _phonebookService.RemoveContact(id);
            TempData.Add("toast", "Contato removido com sucesso");
            return Content(Url.Action("Index"));
        }

        private async Task<SelectList> GetTelephoneTypeSelectList()
        {
            var telephoneTypes = await _phonebookService.GetTelephoneTypes();
            var items = telephoneTypes.Select(tt => new { tt.Id, Text = tt.Name }).ToList();
            return new SelectList(items, "Id", "Text");
        }

    }
}

Agenda.MVC/Views/Phonebook/Index.cshtml
@model PhonebookViewModel

@{
  Layout = "_PhonebookLayout";
}

@using (Html.BeginForm("Index", "Phonebook", FormMethod.Get)) {
  <div class="row">
    <div class="col m3">
      <div class="card">
        <div class="card-content">

          <h5 class="center-align" style="font-weight:bold">Busca</h5>

          <div class="input-field m1">
            @Html.LabelFor(m => m.SearchParameters.IdContato, htmlAttributes: new { @class = "active" })
            @Html.TextBoxFor(m => m.SearchParameters.IdContato, new { @class = "validate" })
          </div>

          <div class="input-field m1">
            @Html.LabelFor(m => m.SearchParameters.NomeContato, htmlAttributes: new { @class = "active" })
            @Html.TextBoxFor(m => m.SearchParameters.NomeContato, new { @class = "validate" })
          </div>

          <div class="input-field m1">
            @Html.LabelFor(m => m.SearchParameters.Ddd, htmlAttributes: new { @class = "active" })
            @Html.TextBoxFor(m => m.SearchParameters.Ddd, new { @class = "validate" })
          </div>

          <div class="input-field m1">
            @Html.LabelFor(m => m.SearchParameters.NumeroTelefone, htmlAttributes: new { @class = "active" })
            @Html.TextBoxFor(m => m.SearchParameters.NumeroTelefone, new { @class = "validate" })
          </div>

        </div>
        <div class="card-footer right-align">
          <button><i class="material-icons">search</i></button>
        </div>
      </div>
    </div>

    <div class="col m7">
      <br />
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Primeiro telefone</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          @foreach (var contact in Model.Contacts) {
            <tr>
              <td>@contact.Id</td>
              <td>@contact.Name</td>
              <td>
                @(contact.Telephones.FirstOrDefault() == null ? "-" :
                        contact.Telephones.FirstOrDefault().TelephoneFormatted)
              </td>
              <td>
                <a data-contactId="@contact.Id"
                   href="@Url.Action("Details", "Phonebook", new { id = contact.Id })">
                  <i class="material-icons">visibility</i>
                </a>
                <a data-contactId="@contact.Id" href="@Url.Action("Form", "Phonebook", new { id = contact.Id })"
                   class="editContactIcn"><i class="material-icons">edit</i></a>
                <a data-contactId="@contact.Id" href="#!" class="removeContactIcn">
                  <i class="material-icons">delete</i>
                </a>
              </td>
            </tr>
          }
        </tbody>
        <tfoot>
        </tfoot>
      </table>
    </div>

    <div class="fixed-action-btn">
      <a href="@Url.Action("Form", "Phonebook", new { id = 0 })"
         class="btn-floating btn-large waves-effect waves-light red">
        <i class="material-icons">add</i>
      </a>
    </div>

    @if (Model.Contacts.Any()) {
      <div class="col m12 center">
        <ul class="pagination">
          <li>
            <button @(Model.SearchParameters.Page == 1 ? "disabled" : "") type="submit" name="SearchParameters.Page"
                    value="@(Model.SearchParameters.Page - 1)">
              <i class="material-icons" type="submit">chevron_left</i>
            </button>
          </li>
          @for (int i = 1; i <= Model.SearchParameters.HowManyPages; i++) {
            <li class="@(Model.SearchParameters.Page == i ? "active" : "")">
              <button type="submit" name="SearchParameters.Page" value="@i">@i</button>
            </li>
          }
          <li>
            <button @(Model.SearchParameters.Page == Model.SearchParameters.HowManyPages ? "disabled" : "")
                    type="submit" name="SearchParameters.Page" value="@(Model.SearchParameters.Page + 1)">
              <i class="material-icons" typeof="submit">chevron_right</i>
            </button>
          </li>
        </ul>
      </div>
    }

  </div>
}

@*REMOVE CONTACT MODAL*@
<div id="removeContactModal" class="modal">
  <div class="modal-content">
    <h5 class="card-title" style="font-weight:bold">
      Remover contato
    </h5>
    <p>Tem certeza que deseja remover esse contato permanentemente?</p>
    <div class="modal-footer">
      <a id="removeContactModalConfirmBtn" href="#!" class="waves-effect waves-light btn">
        SIM
      </a>
      <a href="#!" class="waves-effect waves-light btn close-modal-btn modal-close">
        NÃO
      </a>
    </div>
  </div>
</div>

@section Scripts
{
  <script>
    $(document).ready(function () {
      $('.modal').modal();
      $('.collapsible').collapsible
      $('.fixed-action-btn').floatingActionButton();

      $('.removeContactIcn').click(function () {
        var contactId = $(this).attr('data-contactId');

        $('#removeContactModal').modal('open');
        $('#removeContactModalConfirmBtn').attr('data-contactId', contactId);
      });

      $('#removeContactModalConfirmBtn').click(function () {
        var contactId = $(this).attr('data-contactId');
        var url = '/agenda/remover?id=' + contactId;

        $.post(url, function (response) {
          window.location = response;
        });
      });
    });
  </script>
}