Agenda.MVC/ViewModels/Contact/ContactFormViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Agenda.MVC.ViewModels.ContactTelephone;

namespace Agenda.MVC.ViewModels.Contact
{
    public class ContactFormViewModel
    {

        public int Id { get; set; }

        [Required(ErrorMessage = "O nome não pode estar vazio")]
        [DisplayName("Nome")]
        public string Name { get; set; }

        [DisplayName("Dono")]
        public string OwnerId { get; set; }

        [Required]
        [DisplayName("Telefones")]
        public List<ContactTelephoneFormViewModel> Telephones { get; set; } = new List<ContactTelephoneFormViewModel>();

    }
}

Agenda.MVC/ViewModels/Contact/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Agenda.MVC.ViewModels.ContactTelephone;

namespace Agenda.MVC.ViewModels.Contact
{
    public class ContactViewModel : RecordViewModel
    {

        [Required]
        [DisplayName("Nome")]
        public string Name { get; set; }

        [DisplayName("Dono")]
        public UserViewModel Owner { get; set; }

        [Required]
        [DisplayName("Telefones")]
        public List<ContactTelephoneViewModel> Telephones { get; set; } = new List<ContactTelephoneViewModel>();

    }
}

Agenda.MVC/Controllers/Admin/InteractionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Agenda.MVC.ApiHttpServices;
using Agenda.MVC.ViewModels;
using Agenda.MVC.ViewModels.ApiResponse;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Agenda.MVC.Controllers
{
    [Authorize(Roles = "ADMIN")]
    [Route("interacoes")]
    public class InteractionsController : Controller
    {

        private readonly InteractionsService _interactionService;

        public InteractionsController(InteractionsService interactionService)
        {
            _interactionService = interactionService;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var interactionPagination = await _interactionService.GetInteractionPage(page);

            ViewBag.totalPages = Math.Ceiling((double)interactionPagination.Total / 6);
            ViewBag.currentPage = page;

            return View(interactionPagination.Data);
        }

    }
}

Agenda.MVC/Controllers/Admin/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Agenda.MVC.ApiHttpServices;
using Agenda.MVC.ViewModels;
using Agenda.MVC.ViewModels.ApiResponse;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Agenda.MVC.Controllers
{
    [Authorize(Roles = "ADMIN")]
    [Route("gerenciamento-usuarios")]
    public class UserManagementController : Controller
    {

        private readonly UserManagementService _userService;
        private readonly IMapper _mapper;

        public UserManagementController(UserManagementService userService,
            IMapper mapper)
        {
            _userService = userService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var userPagination = await _userService.GetUserPage(page);

            ViewBag.totalPages = Math.Ceiling((double)userPagination.Total / 6);
            ViewBag.currentPage = page;

            var userIndexVm = new UserIndexViewModel() {
                Users = userPagination.Data,
                ModalForm = null
            };

            return View(userIndexVm);
        }

        [HttpGet]
        [Route("form")]
        public async Task<ActionResult> GetUserForm(int? id)
        {
            UserFormViewModel userFormVm = null;

            if (id.HasValue)
            {
                var user = await _userService.GetUser((int)id);
                userFormVm = _mapper.Map<UserFormViewModel>(user);
            }

            TempData["Roles"] = await GetUserRolesSelectList();

            return PartialView("_UserForm", userFormVm);
        }

        [HttpPost]
        public async Task<ActionResult> Index(int page, UserFormViewModel model)
        {
            ApiResponseViewModel<UserViewModel> apiResponse;

            if (string.IsNullOrEmpty(model.Id))
            {
                apiResponse = await _userService.AddUser(model);
                TempData.Add("toast", "Usuário adicionado com sucesso");
            }
            else
            {
                apiResponse = await _userService.UpdateUser(model);
                TempData.Add("toast", "Usuário atualizado com sucesso");
            }

            if (!apiResponse.HasError)
            {
                return RedirectToAction("Index");
            }

            var userPagination = await _userService.GetUserPage(page);
            apiResponse.AddErrorsToModelState(ModelState);
            TempData.Remove("toast");

            var userIndexVm = new UserIndexViewModel()
            {
                Users = userPagination.Data,
                ModalForm = model
            };

            ViewBag.totalPages = Math.Ceiling((double)userPagination.Total / 6);
            ViewBag.currentPage = page;
            TempData["Roles"] = await GetUserRolesSelectList();

            return View(userIndexVm);
        }

        [HttpPost]
        [Route("remover")]
        public async Task<ActionResult> RemoveUser(int id)
        {
            await _userService.RemoveUser(id);
            TempData.Add("toast", "Usuário removido com sucesso");
            return Content(Url.Action("Index"));
        }

        private async Task<SelectList> GetUserRolesSelectList()
        {
            var roles = await _userService.GetUserRoles();
            return new SelectList(roles, "Id", "Name", 2);
        }

    }
}

Agenda.MVC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Agenda.MVC.ApiHttpServices;
using Agenda.MVC.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Agenda.MVC.Controllers
{

    public class LoginController : Controller
    {

        private readonly LoginService _apiHttpService;

        public LoginController(LoginService apiHttpService)
        {
            _apiHttpService = apiHttpService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (Request.Cookies["HasLoggedIn"] != null)
            {
                TempData.Add("toast", "Sua sessão expirou");
                Response.Cookies.Delete("HasLoggedIn");
            }

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(LoginViewModel loginViewModel)
        {
            var token = await _apiHttpService.Login(loginViewModel);

            if (token == null)
            {
                ModelState.AddModelError(string.Empty, "Username ou senha inválidos");
                return View(loginViewModel);
            }

            var decodedToken = DecodeToken(token);
            var claims = decodedToken.Claims.Concat(new[] { new Claim("jwt-token", token) });
            var cookieClaims = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme, "unique-name", "role");

            Response.Cookies.Append("HasLoggedIn", "true");

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(cookieClaims),
                GetAuthProperties());

            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public async Task<ActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            Response.Cookies.Delete("HasLoggedIn");
            return Redirect(Url.Action("Index"));
        }

        private JwtSecurityToken DecodeToken(string jwtToken)
        {
            var handler = new JwtSecurityTokenHandler();
            var jsonToken = handler.ReadToken(jwtToken);
            var decodedToken = jsonToken as JwtSecurityToken;

            return decodedToken;
        }

        private AuthenticationProperties GetAuthProperties()
        {
            return new()
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddHours(1),
                IsPersistent = true,
                RedirectUri = "/"
            };
        }

    }
}

Agenda.MVC/Views/Shared/_ContactDetails.cshtml
@model ContactViewModel;

<div class="row">
  <div class="col m12">
    <div class="card">
      <div class="card-content">
        <span class="card-title" style="font-weight:bold">Contato</span>
        <dl>
          <dt>
            ID:
          </dt>
          <dd>
            @Html.DisplayFor(model => model.Id)
          </dd>
          <dt>
            Nome:
          </dt>
          <dd>
            @Html.DisplayFor(model => model.Name)
          </dd>
          <dt>
            Data criação:
          </dt>
          <dd>
            @(Model.CreationDate.ToLocalTime())
          </dd>
          <dt>
            Data última atualização:
          </dt>
          <dd>
            @(Model.LastUpdateDate == null ? "-" : ((DateTime)Model.LastUpdateDate).ToLocalTime())
          </dd>
          <dt>
            <br />
            Telefones:
          </dt>
          <dd>
            <table class="table">
              <tr>
                <th>ID</th>
                <th>Número</th>
                <th>Descrição</th>
                <th>Tipo</th>
                <th>Data criação</th>
                <th>Data da última atualização</th>
              </tr>
              @foreach (var tel in Model.Telephones) {
                <tr>
                  <td>
                    @Html.DisplayFor(t => tel.Id)
                  </td>
                  <td>
                    @Html.DisplayFor(t => tel.TelephoneFormatted)
                  </td>
                  <td>
                    @Html.DisplayFor(t => tel.Description)
                  </td>
                  <td>
                    @Html.DisplayFor(t => tel.Type)
                  </td>
                  <td>
                    @(tel.CreationDate.ToLocalTime())
                  </td>
                  <td>
                    @(tel.LastUpdateDate == null ? "-" : ((DateTime)tel.LastUpdateDate).ToLocalTime())
                  </td>
                </tr>
              }
            </table>
          </dd>
        </dl>
      </div>
    </div>
  </div>
</div>

@if (User.IsInRole("ADMIN")) {
  <div class="row">
    <div class="col m12">
      <div class="card">
        <div class="card-content">
          <span class="card-title" style="font-weight:bold">Dono</span>
          <dl>
            <dt>
              ID:
            </dt>
            <dd>
              @Html.DisplayFor(model => model.Owner.Id)
            </dd>
            <dt>
              Role:
            </dt>
            <dd>
              @Html.DisplayFor(model => model.Owner.Role)
            </dd>
            <dt>
              Username:
            </dt>
            <dd>
              @Html.DisplayFor(model => model.Owner.Username)
            </dd>
            <dt>
              Nome:
            </dt>
            <dd>
              @Html.DisplayFor(model => model.Owner.Name)
            </dd>
            <dt>
              Email:
            </dt>
            <dd>
              @Html.DisplayFor(model => model.Owner.Email)
            </dd>
            <dt>
              Data criação:
            </dt>
            <dd>
              @(Model.Owner.CreationDate.ToLocalTime())
            </dd>
            <dt>
              Data última atualização:
            </dt>
            <dd>
              @(Model.Owner.LastUpdateDate == null ? "-" :
                        ((DateTime)Model.Owner.LastUpdateDate).ToLocalTime())
            </dd>
          </dl>
        </div>
      </div>
    </div>
  </div>
}

Agenda.MVC/Views/Shared/_ContactForm.cshtml
@model ContactFormViewModel;

@{
  var users = (SelectList)ViewBag.users;
  var telephoneTypes = (SelectList)ViewBag.telephoneTypes;

  var contactNameDivClass = User.IsInRole("ADMIN") ? "input-field col m6" : "input-field col m12";
  var controllerName = User.IsInRole("ADMIN") ? "ContactManagement" : "Phonebook";
}

<div class="row">
  <div class="col m12">
    <div class="card">
      <div class="card-content">
        <span class="card-title" style="font-weight:bold">
          @(Model.Id == 0 ? "Adicionar Contato" : "Editar Contato")
        </span>
        @using (Html.BeginForm("Form", controllerName, FormMethod.Post)) {
          @Html.HiddenFor(c => c.Id)

          <div class="row">

            <div class="@contactNameDivClass">
              @Html.LabelFor(c => c.Name, htmlAttributes: new { @class = "active" })
              @Html.TextBoxFor(c => c.Name, new { @class = "validate" })
              @Html.ValidationMessageFor(c => c.Name, null, new { @class = "validation-message" })
            </div>

            @if (User.IsInRole("ADMIN")) {
              <div class="input-field col m6">
                @Html.LabelFor(c => c.OwnerId, new { @class = "active" })
                @Html.DropDownListFor(c => c.OwnerId, (SelectList)ViewBag.users)
              </div>
            }

          </div>

          <div class="row">
            <div class="col m12">
              <table>
                <thead>
                  <tr>
                    <th>Número</th>
                    <th>Descrição</th>
                    <th>Tipo</th>
                    <th></th>
                  </tr>
                </thead>
                @Html.LabelFor(c => c.Telephones)
                @for (int i = 0; i < Model.Telephones.Count; i++) {
                  <tr class="telephone-row">
                    <td id="telephone-type-@i">
                      @Html.TextBoxFor(c => c.Telephones[i].TelephoneNumber, new { @class = "validate telephone-number" })
                      @Html.ValidationMessageFor(c => c.Telephones[i].TelephoneNumber, null, new { @class = "validation-message" })
                    </td>
                    <td>
                      @Html.TextBoxFor(c => c.Telephones[i].Description, new { @class = "validate" })
                      @Html.ValidationMessageFor(c => c.Telephones[i].Description, null, new { @class = "validation-message" })
                    </td>
                    <td id="telephone-type-@i">
                      @Html.DropDownListFor(c => c.Telephones[i].Type, telephoneTypes, htmlAttributes: new { @class = "validate telephone-type" })
                    </td>
                    <td>
                      <button name="option" class="waves-effect waves-light btn-flat cancel" type="submit"
                              value="removeTelephone|@i">
                        <i class="material-icons">delete</i>
                      </button>
                    </td>
                  </tr>
                }
              </table>
              <br />
              <div class="row center-align validation-message">
                @Html.ValidationSummary(true)
              </div>
              <button name="option" class="right waves-effect waves-light btn cancel" type="submit" value="addTelephone">
                Adicionar telefone
              </button>
            </div>
          </div>

          <div class="row">
            <a href="@Url.Action("Index", controllerName)"
               class="btn option-btn waves-effect waves-light right">Cancelar</a>
            <button name="option" class="btn option-btn waves-effect waves-light right" type="submit" value="save">
              @(Model.Id == 0 ? "Adicionar" : "Atualizar")
            </button>
          </div>
        }
      </div>
    </div>
  </div>
</div>

@section Scripts
{
  @await Html.PartialAsync("_ValidationScriptsPartial")
  <script src="~/js/contactFormValidationScripts.js"></script>

  <script>
    $(document).ready(function () {
      $('select').formSelect();

      $('.telephone-type').change(function (event) {
        var currentRow = $(this).attr('name').split("[")[1][0];
        $('#Telephones_' + currentRow + '__TelephoneNumber').val('');
      });
    });
  </script>
}

Agenda.MVC/Views/Shared/_Layout.cshtml
<html>

<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/fontawesome.min.css"
        integrity="sha512-OdEXQYCOldjqUEsuMKsZRj93Ht23QRlhIb8E/X0sbwZhme8eUw6g8q7AdxGJKakcBbv7+/PX0Gc2btf7Ru8cZA=="
        crossorigin="anonymous" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="~/css/site.css">

</head>

<body>

  <header>
    <nav>
      <div class="nav-wrapper">
        <a href="@Url.Action("Index", "Home")" class="brand-logo">Logo</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          @if (User.Identity.IsAuthenticated) {
            var role = User.Claims.FirstOrDefault(c => c.Type.Equals("role")).Value;

            @if (role.Equals("STANDARD USER")) {
              <li><a href=@Url.Action("Index", "Phonebook")>Agenda</a></li>
            }

            @if (role.Equals("ADMIN")) {
              <li><a href=@Url.Action("Index", "ContactManagement")>Contatos</a></li>
              <li><a href=@Url.Action("Index", "UserManagement")>Usuários</a></li>
              <li><a href=@Url.Action("Index", "Interactions")>Interações</a></li>
            }

            <li><a href=@Url.Action("Logout", "Login")>LOG OUT</a></li>
          } else {
            <li><a href="@Url.Action("Index", "Login")">Login</a></li>
          }
        </ul>
      </div>
    </nav>

  </header>

  <main>
    <div class="container ">
      @RenderBody()
    </div>
  </main>

  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Agenda do Raul</h5>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        © 2021 NoCopyright
        <div class="grey-text text-lighten-4 right">Raul Alves Reginaldo</div>
      </div>
    </div>
  </footer>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
          integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  @await RenderSectionAsync("Scripts", required: false)

  @if (TempData.TryGetValue("toast", out var msg)) {
    <script>
            document.addEventListener('DOMContentLoaded', function () {
                M.toast({ html: '@Html.Raw(msg)' });
            });
    </script>
  }

</body>

</html>

Agenda.MVC/Views/Shared/_PhonebookLayout.cshtml
<html>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/fontawesome.min.css"
        integrity="sha512-OdEXQYCOldjqUEsuMKsZRj93Ht23QRlhIb8E/X0sbwZhme8eUw6g8q7AdxGJKakcBbv7+/PX0Gc2btf7Ru8cZA=="
        crossorigin="anonymous" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="~/css/site.css">

</head>

<body>

  <header>
    <nav>
      <div class="nav-wrapper">
        <a href="@Url.Action("Index", "Home")" class="brand-logo">Logo</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          @if(User.Identity.IsAuthenticated)
           {
              var role = User.Claims.FirstOrDefault(c => c.Type.Equals("role")).Value;

              @if (role.Equals("STANDARD USER"))
              {
                  <li><a href=@Url.Action("Index", "Phonebook")>Agenda</a></li>
               }

              @if(role.Equals("ADMIN"))
               {
                  <li><a href=@Url.Action("Index", "ContactManagement")>Contatos</a></li>
                  <li><a href=@Url.Action("Index", "UserManagement")>Usuários</a></li>
                  <li><a href=@Url.Action("Index", "Interaction")>Interações</a></li>
               }

              <li><a href=@Url.Action("Logout", "Login")>LOG OUT</a></li>
            }
           else
            {
              <li><a href="@Url.Action("Index", "Login")">Login</a></li>
            }
        </ul>
      </div>
    </nav>

  </header>

  <main>
      @RenderBody()
  </main>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"
          integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  @await RenderSectionAsync("Scripts", required: false)

  @if(TempData.TryGetValue("toast", out var msg))
    {
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          M.toast({html: '@Html.Raw(msg)'});
        });
      </script>    
    }

</body>
</html>