Agenda.MVC/Controllers/Admin/ContactManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Agenda.MVC.ApiHttpServices;
using Agenda.MVC.ViewModels.ApiResponse;
using Agenda.MVC.ViewModels.Contact;
using Agenda.MVC.ViewModels.ContactTelephone;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Agenda.MVC.Controllers
{

    [Authorize(Roles = "ADMIN")]
    [Route("gerenciamento-contatos")]
    public class ContactManagementController : Controller
    {

        private readonly ContactManagementService _contactManagementService;
        private readonly UserManagementService _userManagemmentService;
        private readonly IMapper _mapper;

        public ContactManagementController(ContactManagementService contactManagementService, IMapper mapper, UserManagementService userManagemmentService)
        {
            _contactManagementService = contactManagementService;
            _mapper = mapper;
            _userManagemmentService = userManagemmentService;
        }

        public async Task<ActionResult> Index(int page = 1)
        {
            var contactPagination = await _contactManagementService.GetContactPage(page);

            ViewBag.totalPages = Math.Ceiling((double)contactPagination.Total / 6);
            ViewBag.currentPage = page;

            return View(contactPagination.Data);
        }

        [HttpGet]
        [Route("detalhes/{id:int}")]
        public async Task<ActionResult> Details(int id)
        {
            var contactVm = await _contactManagementService.GetContact(id);

            return View("_ContactDetails", contactVm);
        }

        [HttpGet]
        [Route("form/{id:int}")]
        public async Task<ActionResult> Form(int id)
        {
            ContactFormViewModel contactFormVm = new ContactFormViewModel();
            ViewBag.telephoneTypes = await GetTelephoneTypeSelectList();
            ViewBag.users = await GetUsersSelectList();

            if (id != 0)
            {
                var contactVm = await _contactManagementService.GetContact(id);
                contactFormVm = _mapper.Map<ContactFormViewModel>(contactVm);
            }

            return View("_ContactForm", contactFormVm);
        }

        [HttpPost]
        [Route("form/{id:int}")]
        public async Task<ActionResult> Form(ContactFormViewModel model, string option = "save")
        {
            ViewBag.telephoneTypes = await GetTelephoneTypeSelectList();
            ViewBag.users = await GetUsersSelectList();

            if (option.Equals("save"))
            {
                ApiResponseViewModel<ContactViewModel> apiResponse;

                if (model.Id == 0)
                {
                    apiResponse = await _contactManagementService.AddContact(model);
                    TempData.Add("toast", "Contato adicionado com sucesso");
                }
                else
                {
                    apiResponse = await _contactManagementService.UpdateContact(model);
                    TempData.Add("toast", "Contato atualizado com sucesso");
                }

                if (apiResponse.HasError)
                {
                    apiResponse.AddErrorsToModelState(ModelState);
                    TempData.Remove("toast");
                    return View("_ContactForm", model);
                }

                return RedirectToAction("Index");
            }

            if (option.Equals("addTelephone"))
            {
                ModelState.Clear();
                model.Telephones.Add(new ContactTelephoneFormViewModel());
            }

            if (option.Contains("removeTelephone"))
            {
                int indexRemovedTelephone = int.Parse(option.Split("|")[1]);
                ModelState.Clear();
                model.Telephones.RemoveAt(indexRemovedTelephone);
            }

            return View("_ContactForm", model);
        }

        [HttpPost]
        [Route("remover")]
        public async Task<ActionResult> RemoveContact(int id)
        {
            await _contactManagementService.RemoveContact(id);
            TempData.Add("toast", "Contato removido com sucesso");
            return Content(Url.Action("Index"));
        }

        private async Task<SelectList> GetUsersSelectList()
        {
            var users = await _userManagemmentService.GetAllUsers();
            var items = users.Select(u => new { u.Id, Text = u.Username }).ToList();
            return new SelectList(items, "Id", "Text");
        }

        private async Task<SelectList> GetTelephoneTypeSelectList()
        {
            var telephoneTypes = await _contactManagementService.GetTelephoneTypes();
            var items = telephoneTypes.Select(tt => new { tt.Id, Text = tt.Name }).ToList();
            return new SelectList(items, "Id", "Text");
        }

    }
}

Agenda.MVC/Views/ContactManagement/Index.cshtml
@model IEnumerable<ContactViewModel>

@{
    var currentPage = (int)ViewBag.currentPage;
    var totalPages = (int)ViewBag.totalPages;
    var untilPage = currentPage + 17 > totalPages ? totalPages : currentPage + 17;
}

@*REMOVE CONTACT MODAL*@
<div id="removeContactModal" class="modal">
  <div class="modal-content">
    <h5 class="card-title" style="font-weight:bold">
      Remover contato
    </h5>
    <p>Tem certeza que deseja remover esse contato permanentemente?</p>
    <div class="modal-footer">
      <a id="removeContactModalConfirmBtn" href="#!" class="waves-effect waves-light btn">
        SIM
      </a>
      <a href="#!" class="waves-effect waves-light btn close-modal-btn modal-close">
        NÃO
      </a>
    </div>
  </div>
</div>

@using (Html.BeginForm("Index", "ContactManagement", FormMethod.Get)) {
  <div class="row">
    <div class="col m12">

      <h4 class="center-align" style="font-weight:bold">Contatos</h4>

      <table>

        <thead>
          <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Primeiro telefone</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          @foreach (var contact in Model) {
            <tr>
              <td>@contact.Id</td>
              <td>@contact.Name</td>
              <td>
                @(contact.Telephones.FirstOrDefault() == null ? "-" :
                        contact.Telephones.FirstOrDefault().TelephoneFormatted)
              </td>
              <td>
                <a data-contactId="@contact.Id"
                   href="@Url.Action("Details", "ContactManagement", new { id = contact.Id })">
                  <i class="material-icons">visibility</i>
                </a>
                <a data-contactId="@contact.Id"
                   href="@Url.Action("Form", "ContactManagement", new { id = contact.Id })"
                   class="editContactIcn"><i class="material-icons">edit</i></a>
                <a data-contactId="@contact.Id" href="#!" class="removeContactIcn">
                  <i class="material-icons">delete</i>
                </a>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  </div>

  @if (Model.Any()) {
    <div class="col m12 center">
      <ul class="pagination">
        <li>
          <button @(currentPage == 1 ? "disabled" : "") type="submit" name="page" value="1">
            <i class="material-icons" type="submit">chevron_left</i>
          </button>
        </li>
        @for (int i = 1; i <= totalPages; i++) {
          <li class="@(currentPage == i ? "active" : "")">
            <button type="submit" name="page" value="@i">@i</button>
          </li>
        }
        <li>
          <button @(currentPage == totalPages ? "disabled" : "") type="submit" name="page" value="@totalPages">
            <i class="material-icons" typeof="submit">chevron_right</i>
          </button>
        </li>
      </ul>
    </div>
  }
}

<div class="fixed-action-btn">
  <a href="@Url.Action("Form", "ContactManagement", new { id = 0 })"
     class="btn-floating btn-large waves-effect waves-light red">
    <i class="material-icons">add</i>
  </a>
</div>

@section Scripts
{
  <script>
    $(document).ready(function () {
      $('.modal').modal();
      $('.fixed-action-btn').floatingActionButton();

      $('.removeContactIcn').click(function () {
        var contactId = $(this).attr('data-contactId');

        $('#removeContactModal').modal('open');
        $('#removeContactModalConfirmBtn').attr('data-contactId', contactId);
      });

      $('#removeContactModalConfirmBtn').click(function () {
        var contactId = $(this).attr('data-contactId');
        var url = '/gerenciamento-contatos/remover?id=' + contactId;

        $.post(url, function (response) {
          window.location = response;
        });
      });
    });
  </script>
}